# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c9ef4cb67db9fa6ec33e0d8b366174456b1c695a53d63111cc34e8729083b51d133514f862a001a01fe1539f45dbc87689720058181bb7eeadb1637a6da0576

test:
  secret_key_base: 68de9f9b3065f2db242b8ee7010eea8aea83c527fd54ade7fad78179a1c0a37e6b651ea78a50f1b2752a3c5583e0a57909d93866a4b41a4a6c7740f31b6c06e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
